using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WpfApp2
{
    public static class Names
    {
        public static List<string> BankNames()
        {
            var banks = new List<string>();
            banks.Add("Industrial and Commercial Bank of China");
            banks.Add("China Construction Bank Corporation");
            banks.Add("Agricultural Bank of China");
            banks.Add("Bank of China");
            banks.Add("Mitsubishi UFJ Financial Group");
            banks.Add("JPMorgan Chase & Co.");
            banks.Add("HSBC Holdings PLC");
            banks.Add("BNP Paribas");
            banks.Add("Bank of America");
            banks.Add("Crédit Agricole");
            banks.Add("Wells Fargo & Co.");
            banks.Add("Japan Post Bank");
            banks.Add("Citigroup Inc.");
            banks.Add("Sumitomo Mitsui Financial Group");
            banks.Add("Deutsche Bank");
            banks.Add("Banco Santander");
            banks.Add("Mizuho Financial Group");
            banks.Add("Barclays PLC");
            banks.Add("Société Générale");
            banks.Add("Groupe BPCE");
            banks.Add("Bank of Communications");
            banks.Add("Postal Savings Bank of China");
            banks.Add("Lloyds Banking Group");
            banks.Add("Royal Bank of Canada");
            banks.Add("Toronto-Dominion Bank");
            banks.Add("ING Group");
            banks.Add("Norinchukin Bank");
            banks.Add("UniCredit");
            banks.Add("Royal Bank of Scotland Group");
            banks.Add("Industrial Bank (China)");
            banks.Add("China Merchants Bank");
            banks.Add("Intesa Sanpaolo");
            banks.Add("Shanghai Pudong Development Bank");
            banks.Add("UBS");
            banks.Add("Goldman Sachs");
            banks.Add("China Minsheng Bank");
            banks.Add("China CITIC Bank");
            banks.Add("Morgan Stanley");
            banks.Add("Crédit Mutuel");
            banks.Add("Credit Suisse");
            banks.Add("Banco Bilbao Vizcaya Argentaria");
            banks.Add("Scotiabank");
            banks.Add("Commonwealth Bank");
            banks.Add("Rabobank");
            banks.Add("Australia and New Zealand Banking Group");
            banks.Add("Nordea");
            banks.Add("Westpac");
            banks.Add("Standard Chartered");
            banks.Add("China Everbright Bank");
            banks.Add("National Australia Bank");
            banks.Add("DZ Bank");
            banks.Add("Bank of Montreal");
            banks.Add("Danske Bank");
            banks.Add("Commerzbank");
            banks.Add("State Bank of India");
            banks.Add("Resona Holdings");
            banks.Add("Cassa Depositi e Prestiti");
            banks.Add("Ping An Bank");
            banks.Add("Canadian Imperial Bank of Commerce");
            banks.Add("Sumitomo Mitsui Trust Holdings");
            banks.Add("Sberbank of Russia");
            banks.Add("The Export-Import Bank of China");
            banks.Add("Ping An Bank");
            banks.Add("ABN AMRO Group NV");
            banks.Add("U.S. Bancorp");
            banks.Add("KB Financial Group");
            banks.Add("Banco do Brasil SA");
            banks.Add("Shinhan Financial Group");
            banks.Add("Nomura Holdings");
            banks.Add("DBS Group Holdings");
            banks.Add("Caixa Economica Federal");
            banks.Add("PNC Financial Services Group");
            banks.Add("Hua Xia Bank");
            banks.Add("Bank of New York Mellon Corp");
            banks.Add("Shinkin Central Bank (SCB)");
            banks.Add("Capital One Financial Corporation");
            banks.Add("Banco Bradesco SA");
            banks.Add("KBC Group NV");
            banks.Add("Bank of Beijing");
            banks.Add("Oversea-Chinese Banking Corp");
            banks.Add("Svenska Handelsbanken");
            banks.Add("Hana Financial Group");
            banks.Add("NongHyup Financial Group");
            banks.Add("Woori Bank");
            banks.Add("DnB ASA");
            banks.Add("Nationwide Building Society");
            banks.Add("Cathay Financial Holding");
            banks.Add("Landesbank Baden-Wurttemberg");
            banks.Add("La Banque Postale");
            banks.Add("Bank of Shanghai");
            banks.Add("Swedbank");
            banks.Add("Bank of Jiangsu");
            banks.Add("Banco Sabadell");
            return banks;
        }
        public static List<string> CompanyNames()
        {
            var companies = new List<string>();
            companies.Add("Saudi Arabian Oil Company");
            companies.Add("Microsoft");
            companies.Add("Apple");
            companies.Add("Amazon");
            companies.Add("Alphabet");
            companies.Add("Facebook");
            companies.Add("Alibaba");
            companies.Add("Tencent Holdings");
            companies.Add("Berkshire Hathaway");
            companies.Add("Johnson & Johnson");
            companies.Add("Visa");
            companies.Add("Walmart");
            companies.Add("Nestlé");
            companies.Add("Roche Holding");
            companies.Add("Procter & Gamble");
            companies.Add("Samsung Electronics");
            companies.Add("UnitedHealth Group");
            companies.Add("Mastercard");
            companies.Add("Taiwan Semiconductor");
            companies.Add("Intel");
            companies.Add("ICBC");
            companies.Add("Verizon Communications");
            companies.Add("Home Depot");
            companies.Add("Kweichow Moutai");
            companies.Add("AT&T");
            companies.Add("Pfizer");
            companies.Add("Merck & Co.");
            companies.Add("Coca-Cola");
            companies.Add("ExxonMobil");
            companies.Add("Walt Disney");
            companies.Add("LVMH Moet Hennessy Louis Vuitton");
            companies.Add("Novartis");
            companies.Add("Ping An Insurance Group");
            companies.Add("Netflix");
            companies.Add("PepsiCo");
            companies.Add("Cisco Systems");
            companies.Add("NVIDIA");
            companies.Add("Toyota Motor");
            companies.Add("Chevron");
            companies.Add("Comcast");
            companies.Add("Raiffeisen Bank International");
            companies.Add("Adobe");
            companies.Add("Oracle");
            companies.Add("China Mobile");
            companies.Add("Abbott Laboratories");
            companies.Add("L'Oréal");
            companies.Add("Eli Lilly");
            companies.Add("Novo Nordisk");
            companies.Add("Salesforce.com");
            companies.Add("PayPal");
            companies.Add("Tesla");
            companies.Add("SAP");
            companies.Add("Amgen");
            companies.Add("McDonald's");
            companies.Add("AstraZeneca");
            companies.Add("Bristol-Myers Squibb");
            companies.Add("Nike");
            companies.Add("Costco Wholesale");
            companies.Add("Thermo Fisher Scientific");
            companies.Add("Medtronic");
            companies.Add("Unilever");
            companies.Add("Royal Dutch Shell");
            companies.Add("ASML Holding");
            companies.Add("Reliance Industries");
            companies.Add("Sanofi");
            companies.Add("AbbVie");
            companies.Add("Wells Fargo");
            companies.Add("Accenture");
            companies.Add("Philip Morris International");
            companies.Add("Danaher");
            companies.Add("NextEra Energy");
            companies.Add("AIA Group");
            companies.Add("IBM");
            companies.Add("Lockheed Martin");
            companies.Add("Broadcom");
            companies.Add("Union Pacific");
            companies.Add("BHP Group");
            companies.Add("Texas Instruments");
            companies.Add("Gilead Sciences");
            companies.Add("American Tower");
            companies.Add("HSBC Holdings");
            companies.Add("GlaxoSmithKline");
            companies.Add("Charter Communications");
            companies.Add("Citigroup");
            companies.Add("Tata Consultancy Services");
            companies.Add("Honeywell International");
            companies.Add("Linde");
            companies.Add("Total");
            companies.Add("CSL");
            companies.Add("Anheuser-Busch InBev");
            companies.Add("Softbank");
            companies.Add("Starbucks");
            companies.Add("British American Tobacco"); //93
            return companies;
        }
        public static List<string> CountryNames()
        {
            var countries = new List<string>();
            countries.Add("Norway");
            countries.Add("Latvia");
            countries.Add("Austria");
            countries.Add("Belgium");
            countries.Add("Denmark");
            countries.Add("Finland");
            countries.Add("France");
            countries.Add("Germany");
            countries.Add("Greece");
            countries.Add("Ireland");
            countries.Add("Italy");
            countries.Add("Luxembourg");
            countries.Add("Netherlands");
            countries.Add("Portugal");
            countries.Add("Spain");
            countries.Add("Sweden");
            countries.Add("United Kingdom");
            countries.Add("Bulgaria");
            countries.Add("Croatia");
            countries.Add("Cyprus");
            countries.Add("Czech Republic");
            countries.Add("Estonia");
            countries.Add("Hungary");
            countries.Add("Lithuania");
            countries.Add("Malta");
            countries.Add("Poland");
            countries.Add("Romania");
            countries.Add("Slovakia");
            countries.Add("Slovenia");
            countries.Add("Iceland");
            countries.Add("Switzerland");
            countries.Add("Australia");
            countries.Add("Canada");
            countries.Add("Japan");
            countries.Add("New Zealand");
            countries.Add("United States");
            countries.Add("Russian Federation");
            countries.Add("Niger");
            countries.Add("Hong Kong");
            countries.Add("Malaysia");
            countries.Add("Philippines");
            countries.Add("Singapore");
            countries.Add("Taiwan");
            countries.Add("Thailand");
            countries.Add("Viet Nam");
            countries.Add("India");
            countries.Add("China");
            countries.Add("Israel");
            countries.Add("Saudi Arabia");
            countries.Add("Turkey");
            countries.Add("United Arab Emirates");
            countries.Add("Mexico");
            countries.Add("Brazil");
            countries.Add("Chile");
            return countries;
        }
    }
}
